version: '3'

services:
  web:
    build: .
    ports:
      - "1337:1337"
    container_name: express
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - DB_NAME=textEdDb
      - DB_USERNAME=dockerUser
      - DB_PASSWORD=dockerPass
      # - MONGO_DATA_DIR=/data/db
    ports:
      - "27017:27017"
    volumes:
      # - "./data/db:/data/db"
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod --bind_ip_all
    container_name: mongodb